### ISSUE TITLE
Compilation error: .\role_manager.go:40:16: undefined: auth0.Auth0

### ISSUE THREAD

**Issue by moshushi1999** [casbin/auth0-role-manager#1]
# github.com/casbin/auth0-role-manager
.\role_manager.go:40:16: undefined: auth0.Auth0
.\role_manager.go:41:17: undefined: auth0.Auth0

Compilation finished with exit code 2

**Comment by hsluoyz** [comment]
Hi @moshushi1999 , this issue has been fixed. Please use the latest commit.
